# Site
repository: fdelbrayelle/fdelbrayelle.github.io
# favicon: images/favicon.ico

# Personal info
name: François Delbrayelle
title: Développeur full-stack
#email: fdelbrayelle@gmail.fr
#website: www.francois-delbrayelle.fr

# Social links
twitter_username: fdelbrayelle
github_username:  fdelbrayelle
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: fdelbrayelle
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: À propos
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour, je suis <strong>développeur full-stack senior, tech lead et formateur</strong>. Je tente également d'appliquer les règles du software craftsmanship au quotidien dans mon travail. Je me passionne pour le développement depuis la fin des années 90 et j'ai <strong>près de 10 ans d'expérience</strong> depuis le DUT informatique que j'ai effectué à Lens et SUPINFO Lille. De <a href="https://www.16personalities.com/fr/la-personnalite-infj" target="_blank">personnalité INFJ-T</a>, je suis particulièrement sensible aux moyens d'expression telle que la communication non violente.

   Je suis plutôt orienté développement backend à la base mais depuis quelques années je m'intéresse également du frontend et notamment à Angular et Vue. Je suis également utilisateur de GNU/Linux et je tente d'avoir des connaissances larges tout en approfondissant mes connaissances back (T-shaped). J'ai travaillé pour plusieurs ESN, dans différents contextes, modes d'organisations, pour des durées variées et dans divers domaines fonctionnels.

  Mes domaines d'expertise principaux sont : <mark>Spring</mark>, <mark>Angular</mark> et <mark>Vue</mark>
  
  Je cherche à développer mes compétences dans : les <mark>micro-services</mark>, les <mark>containers</mark> et le <mark>cloud</mark>

# Projects Section
projects_title: Projets

# Experience Section
experience_title: Expérience

# Education Section
educaton_title: Formation

# More Section
more_title: En savoir plus sur moi
more_content: | # this will include new lines to allow paragraphs
  À venir !
   - TODO

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
