# Site
repository: fdelbrayelle/fdelbrayelle.github.io
# favicon: images/favicon.ico

# Personal info
name: François Delbrayelle
title: Développeur full-stack
#email: fdelbrayelle@gmail.fr
#website: www.francois-delbrayelle.fr

# Social links
twitter_username: fdelbrayelle
github_username:  fdelbrayelle
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: fdelbrayelle
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: À propos
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Je suis <strong>développeur full-stack senior, tech lead et formateur</strong>. Je tente également d'appliquer les règles du software craftsmanship au quotidien dans mon travail. Je me passionne pour le développement depuis la fin des années 90 et j'ai <strong>près de 10 ans d'expérience</strong> depuis le DUT informatique que j'ai effectué à Lens et le master informatique à SUPINFO Lille. De <a href="https://www.16personalities.com/fr/la-personnalite-infj" target="_blank">personnalité INFJ</a>, je suis particulièrement sensible aux moyens d'expression tels que la [CNV](https://fr.wikipedia.org/wiki/Communication_non_violente).

  Je suis plutôt orienté développement backend à la base mais depuis quelques années je m'intéresse également du frontend et notamment à Angular et Vue. Je suis également utilisateur au quotidien de <mark>GNU/Linux</mark> et je tente d'avoir des connaissances larges tout en approfondissant mes connaissances back ("T-shaped"). J'ai travaillé pour plusieurs ESN, en centre de services, en régie, dans différents contextes et modes d'organisation, pour des durées variées et dans divers domaines fonctionnels (gestion documentaire, référencement, merchandising, vente, e-commerce, santé, banque, assurance).

  Mes domaines d'expertise principaux sont l'écosystème <mark>Java EE</mark>, <mark>Spring</mark>, <mark>Angular</mark> et <mark>Vue</mark>.

  Je me retrouve beaucoup dans la notion de ["métarchitecte"](https://www.youtube.com/watch?v=sEK68arLUq0), je remets constamment mes connaissances en question ("Tu sais tout quand tu sais que tu ne sais rien" disait Socrate) et je suis en veille quasi quotidienne en essayant de m'intéresser aux nouveautés, tester certains frameworks et participer à des Meetups. Je suis en recherche constante d'un équilibre, d'un <em>[ikigai](https://fr.wikipedia.org/wiki/Ikigai)</em>. C'est important pour moi de participer à des projets ayant une utilité pour l'intérêt général.
  
  Je cherche à développer mes compétences en particulier dans les <mark>micro-services</mark>, les <mark>containers</mark>, la <mark>programmation réactive</mark> et l'utilisation de certains <mark>clouds providers</mark>. L'un de mes objectifs est également de contribuer plus à des projets open-source.

# Projects Section
projects_title: Projets

# Experience Section
experience_title: Expérience

# Education Section
education_title: Formation

# More Section
more_title: En savoir plus sur moi
more_content: | # this will include new lines to allow paragraphs
  Je pratique plusieurs langues à différentes fréquences :
   - <mark>Français</mark> - Langue maternelle
   - <mark>Anglais</mark> - Niveau intermédiaire avancé : 840 points au TOEIC en mars 2011
   - <mark>Japonais</mark> - Niveau intermédiaire avancé : école japonaise du Nord Pas-de-Calais en 2008/2009 et 2010/2011, Kanji Kentei niveau 5 (漢字検定5級) en janvier 2010 et Japanese Language Proficiency Test N2 (日本語能力試験2級) en février 2014
   - <mark>Espagnol</mark> - Niveau scolaire lycée (LV2), révisions régulières

  Quand on me demande ce que je fais dans la vie j'ai souvent tendance à parler de mes centres d'intérêt et passions :
   - Le <strong>Japon et la langue japonaise</strong> : voyages en octobre 2010, mai 2013 et janvier 2017 et [blog sur la culture nippone](http://www.francois-delbrayelle.fr/blog-japon/) où j'expose mes récits de voyages
   - La découverte et le perfectionnement de langues étrangères : notions en allemand, arabe et langue des signes français (LSF)
   - La pratique de plusieurs <strong>sports</strong> régulièrement (natation, aikido, randonnée, cyclisme)
   - La <strong>lecture</strong> de romans de science-fiction, steampunk et fantasy mais aussi de classiques, livres d'histoire et essais divers
   - La <strong>botanique</strong> que j'ai notamment découverte via le [MOOC Botanique](https://mooc.tela-botanica.org/course/view.php?id=3) de Tela Botanica en 2018

  J'ai suivi également la <strong>formation SST</strong> (sauveteur-secouriste du travail) le 22 octobre 2018 et la formation incendie.<br /><br />

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
